version: '3.1'

services:

  postgres_db:
    image: postgres
    volumes:
      - ./scripts/db:/docker-entrypoint-initdb.d
    ports: 
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: bookstore
      POSTGRES_HOST_AUTH_METHOD: trust
